import type { Content } from "./content-types";

// Buyer guides: answer-first, honest, and each links to the matching service. Written from
// what we have actually built and seen, with no invented statistics.

const g = { kind: "guide" as const, ctaLabel: "Ask us on WhatsApp", datePublished: "2026-10-04" };

export const GUIDES: Content[] = [
  {
    ...g, cluster: "web", slug: "how-to-choose-a-web-development-company-in-vizag",
    path: "/guides/how-to-choose-a-web-development-company-in-vizag", navLabel: "How to choose a web development company in Vizag",
    title: "How to choose a web development company in Vizag",
    description: "A plain checklist for picking a web development company in Visakhapatnam: what to ask, what to look at, and the warning signs worth walking away from.",
    eyebrow: "Guide · hiring a web developer", h1: "How to choose a web development company in Vizag", readMins: 6,
    lede: "Choosing a web development company is mostly about two things: can they show work that is live and working, and will they still be around after launch. Here is how to check both, and what else to ask, written by a Vizag studio that would rather you chose well than chose us.",
    sections: [
      { h: "Start with live work, not slides", p: [
        "Ask for links you can open on your own phone. A live site tells you more than a case study: how fast it loads, whether it works in Telugu, whether the contact form actually reaches someone.",
        "Then ask what the company did on each one. Who designed it, who built it, and is it still running? Work that is live and in daily use is the strongest proof there is.",
      ] },
      { h: "A checklist you can run in an afternoon", p: ["Tick these off as you talk to each company."], checklist: [
        "They showed live sites, not only screenshots",
        "Design and development are done by the same team, or a clear hand-off exists",
        "They asked about your customers and business before talking about technology",
        "They explained what is included, what is not, and what changes cost extra",
        "You know who owns the code, the domain and the hosting account",
        "They set up analytics and search console at launch",
        "They will support you after launch and told you how",
        "The quote is for a defined scope, not a vague number",
        "Telugu or Hindi pages, if you need them, were shown working",
      ] },
      { h: "Questions that separate good from average", p: [
        "Ask how they would build for search. A good answer mentions clean URLs, page titles and descriptions, structured data, fast loading and real content structure, and admits that rankings depend on competition.",
        "Ask what happens when something breaks at 10pm. You are not looking for a promise of instant answers, just an honest one.",
      ] },
      { h: "Warning signs", p: [], bullets: [
        "A price with no scope, or a scope with no questions about your business",
        "Guaranteed first-page rankings",
        "Templates sold as custom design",
        "You do not get the admin login or the source code",
        "Nobody can show you something that is live",
      ] },
      { h: "Where a focused studio fits", p: ["A focused studio gives you senior attention and fast decisions, and a limit on how many projects it takes at once. A large agency gives you depth in numbers. Neither is better in general. Pick based on the size and risk of your project, and talk to the people who will actually do the work."] },
    ],
    faqs: [
      { q: "How much should a website cost in Vizag?", a: "It depends on pages, integrations and whether it needs a database. Beware any number quoted before someone has asked about your business. See our guide on what drives website cost." },
      { q: "Should I choose a local company?", a: "Local helps for meetings and on-site work, but good remote teams do fine. What matters is live work and after-launch support." },
      { q: "How long should a website take?", a: "A focused business site usually takes weeks, not months. Anything with booking, payments or a dashboard takes longer." },
    ],
    related: ["/web-development-company-visakhapatnam", "/guides/what-drives-website-cost-in-india", "/software-development-company-visakhapatnam"],
    keywords: ["how to choose a web development company", "best web development company Vizag", "web development agency Visakhapatnam"],
    ctaMessage: "Hi, I read your guide on choosing a web development company and have a project.", accent: "#8a6d2f",
  },
  {
    ...g, cluster: "clinic", slug: "clinic-appointment-booking-software-buyers-checklist",
    path: "/guides/clinic-appointment-booking-software-buyers-checklist", navLabel: "Clinic booking software buyer's checklist",
    title: "Clinic appointment booking software: a buyer's checklist",
    description: "What to check before you buy appointment booking software for a clinic in India: WhatsApp, payments, Telugu, queue, data and support, as an interactive checklist.",
    eyebrow: "Guide · buying clinic software", h1: "Clinic appointment booking software: a buyer's checklist", readMins: 7,
    lede: "Most clinic booking tools demo well and disappoint at the front desk. This checklist covers what actually matters for an Indian clinic: how patients book, how they pay, what the desk sees, what happens to patient data, and who picks up the phone when something breaks.",
    sections: [
      { h: "How patients book", p: ["Your patients decide whether this works. Check these first."], checklist: [
        "Booking works on a phone browser with no app download",
        "Booking works on WhatsApp, not only on a web page",
        "Telugu, Hindi or your local language is supported properly, not machine translated",
        "Patients can reschedule and cancel without ringing the clinic",
        "A slot is held while the patient pays, and released if they do not",
      ] },
      { h: "Payments", p: ["Money handling is where cheap tools cut corners."], checklist: [
        "UPI and cards are supported",
        "A booking is confirmed automatically when the payment lands",
        "Refunds on cancellation are automatic, or at least one tap",
        "You can see paid, unpaid and refunded at a glance",
      ] },
      { h: "The front desk", p: ["If the desk does not trust it, it will not be used."], checklist: [
        "A live queue with tokens and who is next",
        "Walk-ins can be added in seconds",
        "One switch tells patients the doctor is in, late or away",
        "Reminders go out without anyone remembering to send them",
        "Staff training is part of the offer",
      ] },
      { h: "Data and safety", p: [], checklist: [
        "You know where patient data is stored and who can see it",
        "There are backups, and you know how often",
        "Sensitive actions, such as cancelling, need verification",
        "You can export your own data at any time",
      ] },
      { h: "Support and cost", p: [], checklist: [
        "You know exactly who supports you and how to reach them",
        "WhatsApp message costs from Meta are explained, not hidden",
        "The quote covers setup, training and the first weeks of support",
        "No lock-in that stops you from leaving",
      ] },
      { h: "Know exactly what you are buying", p: ["Be clear about what is included. Some tools do booking only, some add records, prescriptions and insurance billing. Ask which parts exist today and which are promised later, and get it in writing."] },
    ],
    faqs: [
      { q: "How many of these should a good tool tick?", a: "Nearly all of the patient, payment and front desk items. Data and support items are where you separate a serious vendor from a risky one." },
      { q: "Do I need WhatsApp booking?", a: "For most Indian clinics, yes. It is where your patients already are." },
      { q: "Should I pick a ready-made tool or a custom one?", a: "Ready-made is faster to start, custom fits your clinic better. Ask what you would have to change about how you work to use each." },
    ],
    related: ["/appointment-booking-software-for-clinics", "/clinic-management-software-india", "/whatsapp-appointment-booking-for-clinics"],
    keywords: ["clinic appointment software checklist", "how to choose clinic booking software", "clinic software India buying guide"],
    ctaMessage: "Hi, I read your clinic software checklist and want to talk about our clinic.", accent: "#0c7a68",
  },
  {
    ...g, cluster: "clinic", slug: "how-to-reduce-no-shows-at-a-clinic",
    path: "/guides/how-to-reduce-no-shows-at-a-clinic", navLabel: "How to reduce no-shows at a clinic",
    title: "How to reduce no-shows at a clinic: what works in India",
    description: "Practical ways to cut missed appointments at an Indian clinic: pay to confirm, WhatsApp reminders, easy rescheduling and a front desk that can see who is coming.",
    eyebrow: "Guide · fewer missed appointments", h1: "How to reduce no-shows at a clinic", readMins: 5,
    lede: "Patients miss appointments mostly because it is easy to. Three things make it harder without making it unpleasant: ask for commitment when they book, remind them at the right time, and let them move the slot in a tap. Here is how each works, with what we have seen running a live clinic.",
    sections: [
      { h: "1. Ask for commitment up front", p: [
        "A free booking costs the patient nothing to forget. Holding the slot for a short window and confirming it only when the consultation fee is paid changes that. The slot is real to them, and unpaid holds return to the pool for someone else.",
        "This is how the clinic we built for works: a slot is held for fifteen minutes, and a token is issued after payment.",
      ] },
      { h: "2. Remind at the right moment", p: [
        "A reminder the evening before gets read, because it arrives when people plan tomorrow. A reminder two hours before is a useful second net on the same day. Send them on WhatsApp, in the patient's language, with a button to reschedule.",
      ] },
      { h: "3. Make rescheduling easier than skipping", p: [
        "If the only way to change a slot is to phone during clinic hours, patients just do not come. Let them reschedule on the web or WhatsApp, after a one-time code proves it is them. A missed slot should roll to the next working day rather than vanish.",
      ] },
      { h: "A short checklist", p: [], checklist: [
        "Payment or a deposit confirms the slot",
        "Unpaid holds release automatically",
        "A reminder goes out the evening before",
        "Patients can reschedule without calling",
        "Missed slots roll to the next working day",
        "The front desk can see who is paid and who is not",
      ] },
      { h: "A note on honesty", p: ["We do not publish a no-show percentage because we have not measured one that would stand up. If a vendor quotes a precise reduction, ask how it was measured."] },
    ],
    faqs: [
      { q: "Will asking for payment put patients off?", a: "Some, yes. Many clinics find it is accepted when it is simple and refundable. You can also take a smaller deposit." },
      { q: "What if a patient cancels after paying?", a: "Refund them automatically. It builds trust and keeps the system fair." },
      { q: "What is the best reminder time?", a: "The evening before, with a second reminder on the day for same-day slots." },
    ],
    related: ["/appointment-booking-software-for-clinics", "/guides/whatsapp-reminders-for-clinic-appointments", "/dental-clinic-appointment-booking-software"],
    keywords: ["reduce no shows clinic", "missed appointments clinic India", "patient no show solutions"],
    ctaMessage: "Hi, I read your guide on no-shows and want to reduce them at our clinic.", accent: "#0c7a68",
  },
  {
    ...g, cluster: "clinic", slug: "whatsapp-reminders-for-clinic-appointments",
    path: "/guides/whatsapp-reminders-for-clinic-appointments", navLabel: "WhatsApp reminders for clinic appointments",
    title: "WhatsApp reminders for clinic appointments: how to set up",
    description: "How clinics in India can send appointment reminders on WhatsApp: the official API, approved templates, opt-in rules, timing and what it costs.",
    eyebrow: "Guide · WhatsApp reminders", h1: "WhatsApp reminders for clinic appointments", readMins: 5,
    lede: "Yes, a clinic can send appointment reminders on WhatsApp, but only through the official WhatsApp Business Platform with templates Meta has approved. Here is how it works, what to avoid so your number is safe, and how to keep the cost reasonable.",
    sections: [
      { h: "Why the ordinary app will not do", p: [
        "The regular WhatsApp Business app lets you message people manually. It cannot send automatic reminders at scale. For that you need the WhatsApp Business Platform, usually called the API, connected to your own number.",
      ] },
      { h: "The rules that matter", p: [], bullets: [
        "Patients should message you first or have agreed to hear from you",
        "A business-started message must use a template Meta has approved",
        "Templates for confirmation, reminder and cancellation are straightforward to get approved",
        "One-time codes belong in the authentication category, which has its own fixed wording",
      ] },
      { h: "Setting it up", p: ["A clinic needs a verified business, a number to register, templates written and submitted, and a system that sends the message at the right time and records whether it was delivered. We handle the setup with you, including approvals."] },
      { h: "Cost", p: ["Meta charges the clinic directly for business-started conversations. The cost depends on volume and category, and is usually small for a single clinic. A good setup avoids sending anything the patient does not need."] },
      { h: "A reminder checklist", p: [], checklist: [
        "Your own business number is registered with the official platform",
        "Confirmation, reminder and cancellation templates are approved",
        "The reminder includes the date, time and a way to reschedule",
        "Delivery failures are logged, so you notice them",
        "Messages are in the patient's language",
      ] },
    ],
    faqs: [
      { q: "Can I use my regular number?", a: "Often yes, with constraints about using the normal app on the same number. Check before you start." },
      { q: "Is it allowed to send reminders without asking?", a: "Patients should have opted in, for example by booking with you. Keep messages relevant to their appointment." },
      { q: "How soon before should I send a reminder?", a: "The evening before, plus a second on the day for same-day slots." },
    ],
    related: ["/whatsapp-appointment-booking-for-clinics", "/whatsapp-business-automation", "/guides/how-to-reduce-no-shows-at-a-clinic"],
    keywords: ["WhatsApp reminders for clinic appointments", "WhatsApp Business API for clinics", "automatic appointment reminder WhatsApp India"],
    ctaMessage: "Hi, I read your guide on WhatsApp reminders and want to set it up for our clinic.", accent: "#128c4a",
  },
  {
    ...g, cluster: "restaurant", slug: "qr-menu-vs-qr-ordering-for-restaurants",
    path: "/guides/qr-menu-vs-qr-ordering-for-restaurants", navLabel: "QR menu vs QR ordering",
    title: "QR menu vs QR ordering: which does a restaurant need?",
    description: "A QR menu shows dishes. QR ordering takes the order. How they differ, what each costs you in effort, and which one a restaurant or bar should start with.",
    eyebrow: "Guide · restaurant tech", h1: "QR menu vs QR ordering: which does your restaurant need?", readMins: 5,
    lede: "A QR menu shows guests what you serve. QR ordering lets them order and, usually, pay from the table. Most places should start with a good menu and grow into ordering, unless service speed is already the problem. Here is how to decide.",
    sections: [
      { h: "What each one actually is", p: [
        "A QR menu is a page, or too often a PDF, that opens when a guest scans the table code. It reduces printing and makes updates instant.",
        "QR ordering adds a cart. Guests pick dishes, a whole table can add to one cart, and the order goes to the kitchen or the point-of-sale. That changes how your floor works, so it needs more care to roll out.",
      ] },
      { h: "A quick way to decide", p: [], checklist: [
        "Guests wait to be noticed at busy times: consider ordering",
        "Your menu changes often: a digital menu already helps",
        "Large tables order in pieces: group ordering helps",
        "Your kitchen uses a point-of-sale: check ordering can connect to it",
        "You want to upsell pairings and specials: ordering plus an AI host helps",
        "Your staff are nervous about change: start with a menu",
      ] },
      { h: "What good ordering still leaves to people", p: ["The best versions take order-taking off your waiters so they can do hospitality, not replace them. That is how we built it for a Vizag restobar, and why the waiter stays at the centre of the room."] },
      { h: "Pilot before the whole floor", p: ["Run ordering on a few tables first, watch what guests and staff do, and fix what is awkward. A pilot is cheaper than a rollout you regret."] },
    ],
    faqs: [
      { q: "Do guests need to download an app?", a: "No. They scan the table code and the page opens in the browser." },
      { q: "Can I start with a menu and add ordering later?", a: "Yes, if the menu is built on a foundation that supports it." },
      { q: "Will QR ordering reduce my staff?", a: "That is not the goal. It frees waiters for hospitality and helps each one sell more." },
    ],
    related: ["/digital-menu-for-restaurants-and-bars", "/restaurant-qr-ordering-system", "/restaurant-qr-ordering-system-visakhapatnam"],
    keywords: ["QR menu vs QR ordering", "restaurant QR ordering explained", "do I need QR ordering restaurant"],
    ctaMessage: "Hi, I read your QR menu vs ordering guide and want advice for our restaurant.", accent: "#a8651c",
  },
  {
    ...g, cluster: "web", slug: "whatsapp-business-api-vs-whatsapp-business-app",
    path: "/guides/whatsapp-business-api-vs-whatsapp-business-app", navLabel: "WhatsApp Business API vs app",
    title: "WhatsApp Business API vs WhatsApp Business app, explained",
    description: "The WhatsApp Business app is for manual chatting. The API automates bookings, reminders and payments. Which one a clinic, restaurant or shop in India needs.",
    eyebrow: "Guide · WhatsApp for business", h1: "WhatsApp Business API vs WhatsApp Business app", readMins: 5,
    lede: "The WhatsApp Business app is a good free tool for chatting with customers by hand. The WhatsApp Business Platform, or API, is what you need when you want automation: bookings, reminders, payment links and a bot that works while you sleep. Here is the difference, and when to move up.",
    sections: [
      { h: "The app: simple and manual", p: ["It runs on your phone. You get a business profile, a catalogue, quick replies, labels and basic away messages. Someone has to read and answer each chat."] },
      { h: "The API: automation with rules", p: [
        "The Platform connects your number to software. A system can answer questions, book slots, send confirmations and reminders, and share payment links. In return you follow Meta's rules: approved templates for business-started messages, and consent from customers.",
      ] },
      { h: "Which one do you need?", p: [], checklist: [
        "You get the same questions all day: a bot would help",
        "You want automatic reminders or confirmations: you need the API",
        "You need bookings to land in a queue or database: you need the API",
        "Several staff need to share one number: the API, with a shared inbox",
        "You message a handful of customers by hand: the app is enough",
      ] },
      { h: "Costs and catches", p: ["The app is free. The API has Meta's conversation charges plus setup. You also cannot use the regular app and the API on the same number in the usual way, so plan the move rather than stumble into it."] },
    ],
    faqs: [
      { q: "Can I use both on one number?", a: "Not in the usual way. Moving to the API changes how that number works, so we plan it with you." },
      { q: "Is the API hard to set up?", a: "It involves business verification and template approvals. We handle it with you." },
      { q: "Will my customers notice a difference?", a: "They notice faster answers and automatic reminders, and a verified business profile." },
    ],
    related: ["/whatsapp-business-automation", "/whatsapp-appointment-booking-for-clinics", "/guides/whatsapp-reminders-for-clinic-appointments"],
    keywords: ["WhatsApp Business API vs app", "WhatsApp Business API India", "WhatsApp automation for small business"],
    ctaMessage: "Hi, I read your WhatsApp API vs app guide and want to automate our business.", accent: "#128c4a",
  },
  {
    ...g, cluster: "web", slug: "what-drives-website-cost-in-india",
    path: "/guides/what-drives-website-cost-in-india", navLabel: "What drives website cost in India",
    title: "What drives the cost of a website in India",
    description: "Why website quotes in India vary so much: scope, design, integrations, content, languages and support. What to ask for so quotes are comparable.",
    eyebrow: "Guide · website cost", h1: "What drives the cost of a website in India", readMins: 5,
    lede: "Website quotes vary because they are rarely for the same thing. Scope, design depth, integrations, content and support change the number far more than the company's size. We will not print a price list that would be wrong for you, but we can show what moves the cost and how to get quotes you can compare.",
    sections: [
      { h: "The six things that move the number", p: [], bullets: [
        "Scope: how many pages, and whether it needs a database, logins or an admin",
        "Design: a custom identity and layouts versus a lightly adapted template",
        "Integrations: payments, WhatsApp, booking, point-of-sale and email",
        "Content: who writes, photographs and translates it",
        "Languages: Telugu or Hindi done properly takes extra care",
        "Support: what happens after launch, and how fast",
      ] },
      { h: "Why a very low quote should worry you", p: ["A quote far below the rest usually leaves something out: design depth, testing, content, search basics or support. Ask what is not included. Find out who owns the domain, hosting and code."] },
      { h: "How to get quotes you can compare", p: ["Write one short brief and send it to every company, then compare the same list."], checklist: [
        "Pages and features listed",
        "Design: custom or template, number of revisions",
        "Integrations named",
        "Content and photography: who provides it",
        "Languages needed",
        "Launch tasks: analytics, search console, redirects",
        "After-launch support and its cost",
        "Ownership of code, domain and accounts",
      ] },
      { h: "How we quote", p: ["We scope first, usually after a short call, and quote against a written plan. We would rather tell you a project does not need a custom build than sell you one."] },
    ],
    faqs: [
      { q: "Is a template site cheaper?", a: "Usually, and fine for some businesses. Custom design costs more and pays back when the brand and conversion matter." },
      { q: "Do I pay for hosting separately?", a: "Often. Ask which accounts are in your name and what the yearly costs are." },
      { q: "Does a website need ongoing costs?", a: "Hosting, domain and some maintenance, yes. Support after launch is worth agreeing on." },
    ],
    related: ["/web-development-company-visakhapatnam", "/guides/how-to-choose-a-web-development-company-in-vizag", "/ecommerce-website-development-visakhapatnam"],
    keywords: ["website cost in India", "how much does a website cost India", "website development price India"],
    ctaMessage: "Hi, I read your guide on website cost and want a quote for my business.", accent: "#8a6d2f",
  },
];
