import type { Content } from "./content-types";

// Targeted landing pages. Each one is written for a distinct search intent and carries
// details that are true and specific to that intent. No invented clients, numbers or prices.

const ORTHO = {
  label: "Live in a real clinic",
  title: "Ramachandra Ortho Care, Visakhapatnam",
  text: "A single-doctor orthopaedic clinic books through its website and WhatsApp in Telugu, English and Hindi, and runs its day from the live queue we built.",
  href: "/work/ramachandra-ortho",
  cta: "Read the case study",
  img: "/case/ortho/hero-d.webp",
  alt: "Ramachandra Ortho Care booking website with live doctor availability",
};
const SOMAA = {
  label: "Live pilot",
  title: "Somaa, Visakhapatnam",
  text: "A restobar with live music orders from the table on the platform we designed and built, connected to its kitchen's point-of-sale.",
  href: "/work/somaa",
  cta: "Read the case study",
  img: "/case/somaa/step-order.webp",
  alt: "Somaa table ordering on a phone",
};

const clinicCta = { ctaLabel: "Talk to us on WhatsApp", accent: "#0c7a68" };

export const LANDINGS: Content[] = [
  // ---------------------------------------------------------------- clinic: places
  {
    kind: "landing", cluster: "clinic", slug: "clinic-appointment-booking-software-visakhapatnam",
    path: "/clinic-appointment-booking-software-visakhapatnam", navLabel: "Clinic booking software in Visakhapatnam",
    title: "Clinic appointment booking software in Visakhapatnam",
    description: "Online and WhatsApp appointment booking, payments and a live token queue for clinics in Visakhapatnam, built by a Vizag studio that runs one live.",
    eyebrow: "Visakhapatnam clinics", h1: "Clinic appointment booking software in Visakhapatnam",
    lede: "If you run a clinic in Visakhapatnam, we can set up online and WhatsApp booking for it, with pay-to-confirm and a live token queue for your front desk. We are a Vizag studio, so we can sit at your reception on go-live day rather than send you a login and a PDF.",
    sections: [
      { h: "Why a Vizag clinic needs more than a booking form", p: [
        "Most patients in Vizag still ring the clinic or send a WhatsApp message, and many think in Telugu first. A plain form in English misses them. A system that answers on WhatsApp in Telugu, shows whether the doctor is in today and holds a slot until the fee is paid meets them where they are.",
        "It also helps the people behind the desk. Calls, chats and walk-ins end up in one queue, so nobody re-types a booking or double books a time.",
      ] },
      { h: "What we set up for your clinic", p: ["The same system running a live clinic in Chinnamushidiwada, configured for yours:"], bullets: [
        "A booking page with your real schedule, visit types and fees",
        "A WhatsApp assistant on your own clinic number",
        "Online payment to confirm, with automatic refunds on cancellation",
        "A live token queue, walk-in entry and a doctor in, late or away switch",
        "Telugu, English and Hindi across the site and the assistant",
      ] },
      { h: "Areas we work in", p: ["We work with clinics across Visakhapatnam, including Dwaraka Nagar, MVP Colony, Siripuram, Seethammadhara, Madhurawada, Gajuwaka and the Chinnamushidiwada side of the city. We can visit, watch how your desk runs for an hour, and then configure it around what we saw."] },
    ],
    faqs: [
      { q: "Can you come to my clinic in Visakhapatnam?", a: "Yes. We are based in the city and prefer to see the front desk before we configure anything, and to be there on the first day patients use it." },
      { q: "Will my patients be able to book in Telugu?", a: "Yes. Telugu, English and Hindi are built in, on the website and on WhatsApp." },
      { q: "Can you also build patient records and prescriptions?", a: "Yes, as a next phase once booking is running, scoped with you. Or we connect to the records software you already use." },
      { q: "How much does it cost?", a: "We quote after a short walkthrough of your clinic, because a flat number would be wrong for most clinics." },
    ],
    proof: ORTHO, related: ["/appointment-booking-software-for-clinics", "/whatsapp-appointment-booking-for-clinics", "/clinic-appointment-booking-software-andhra-pradesh"],
    keywords: ["clinic appointment booking software Visakhapatnam", "appointment booking system Vizag", "clinic software Vizag"],
    ctaMessage: "Hi, I run a clinic in Visakhapatnam and want online and WhatsApp booking.", ...clinicCta,
  },
  {
    kind: "landing", cluster: "clinic", slug: "clinic-appointment-booking-software-andhra-pradesh",
    path: "/clinic-appointment-booking-software-andhra-pradesh", navLabel: "Clinic booking software in Andhra Pradesh",
    title: "Clinic & hospital appointment booking in Andhra Pradesh",
    description: "Appointment booking, WhatsApp and online payments for clinics and hospitals across Andhra Pradesh, set up remotely by a Visakhapatnam studio.",
    eyebrow: "Andhra Pradesh", h1: "Appointment booking software for clinics and hospitals in Andhra Pradesh",
    lede: "We set up appointment booking for clinics and hospitals across Andhra Pradesh, in Vijayawada, Guntur, Tirupati, Rajahmundry, Kakinada, Nellore and smaller towns, working over video from our studio in Visakhapatnam. Patients book on the web or WhatsApp in Telugu, pay to confirm, and get a token.",
    sections: [
      { h: "Built for how Andhra patients book", p: [
        "Patients here book by phone and WhatsApp, pay by UPI, and often prefer Telugu. The booking page, the WhatsApp assistant and the reminders are all written in everyday Telugu as well as English and Hindi, and payment links accept UPI and cards.",
      ] },
      { h: "How we work with clinics outside Vizag", p: [
        "We start with a video walkthrough of how your day runs, then configure schedule, fees and visit types. We handle the WhatsApp Business setup and payment account with you, send an illustrated handbook for your reception, and stay on call during your first week.",
        "Clinics usually find it easiest to start with one doctor and one front desk, and add more doctors or locations once that is running smoothly.",
      ] },
      { h: "Where this fits", p: ["Single-doctor clinics, small multi-doctor practices and independent specialists are the best fit. Larger hospitals with several departments are possible, but we scope doctors, departments and per-doctor schedules together before building."] },
    ],
    faqs: [
      { q: "Do you work with clinics outside Visakhapatnam?", a: "Yes. Clinics in other Andhra Pradesh towns work with us over video and phone, with a written handbook and launch support." },
      { q: "Can patients pay with UPI?", a: "Yes. Payment links accept UPI and cards, and the booking confirms when the payment lands." },
      { q: "Is the WhatsApp assistant in Telugu?", a: "Yes, written in the Telugu people actually speak, with English and Hindi as well." },
      { q: "Can it work for a hospital with several doctors?", a: "It can, after we scope departments and schedules together. We will tell you plainly if something is not a fit." },
    ],
    proof: ORTHO, related: ["/appointment-booking-software-for-clinics", "/hospital-appointment-booking-system", "/clinic-appointment-booking-software-visakhapatnam"],
    keywords: ["appointment booking software Andhra Pradesh", "hospital appointment booking Andhra Pradesh", "clinic software Vijayawada", "clinic software Guntur"],
    ctaMessage: "Hi, I run a clinic in Andhra Pradesh and want online and WhatsApp booking.", ...clinicCta,
  },
  {
    kind: "landing", cluster: "clinic", slug: "clinic-appointment-booking-software-hyderabad",
    path: "/clinic-appointment-booking-software-hyderabad", navLabel: "Clinic booking software in Hyderabad",
    title: "Clinic appointment booking software for Hyderabad",
    description: "Telugu, English and Hindi appointment booking with WhatsApp and online payment for clinics in Hyderabad and Telangana, set up remotely.",
    eyebrow: "Hyderabad and Telangana", h1: "Clinic appointment booking software for Hyderabad and Telangana",
    lede: "We set up appointment booking for clinics in Hyderabad, Secunderabad and across Telangana. It runs on a web page and on WhatsApp, supports Telugu, Hindi and English, takes payment to confirm a slot, and gives your front desk a live queue. We work remotely from Visakhapatnam.",
    sections: [
      { h: "A city that books in three languages", p: [
        "Hyderabad patients move between Telugu, Hindi, Urdu-inflected Hindi and English in a single conversation. The assistant we build handles Telugu, Hindi and English, and we tune the wording with your desk so it sounds like your clinic and not a translation.",
      ] },
      { h: "Remote setup that does not feel remote", p: [
        "We run a video walkthrough of your day, configure the schedule and fees, set up your WhatsApp Business number and payment account with you, and send a printed handbook for reception. Launch week is monitored closely, and fixes are quick.",
      ] },
      { h: "Neighbourhoods we can serve", p: ["Clinics in Banjara Hills, Jubilee Hills, Madhapur, Kukatpally, Secunderabad, Gachibowli and elsewhere in the city, and in towns across Telangana. Location does not change the setup, since patients book from their phones."] },
    ],
    faqs: [
      { q: "You are in Visakhapatnam. Can you really support a Hyderabad clinic?", a: "Yes. Everything runs online, and the setup is done over video with a written handbook. Vizag and Hyderabad are an overnight train apart if a visit helps." },
      { q: "Does it support Hindi and Urdu-speaking patients?", a: "Hindi and English are supported alongside Telugu. We scope other languages case by case." },
      { q: "Is patient data safe?", a: "It is stored in a managed database with row-level access rules and nightly backups, and used only to run your clinic." },
    ],
    proof: ORTHO, related: ["/appointment-booking-software-for-clinics", "/clinic-appointment-booking-software-andhra-pradesh", "/hospital-appointment-booking-system"],
    keywords: ["clinic appointment booking software Hyderabad", "doctor appointment software Telangana", "WhatsApp booking for clinics Hyderabad"],
    ctaMessage: "Hi, I run a clinic in Hyderabad and want online and WhatsApp booking.", ...clinicCta,
  },
  // ---------------------------------------------------------------- clinic: types
  {
    kind: "landing", cluster: "clinic", slug: "hospital-appointment-booking-system",
    path: "/hospital-appointment-booking-system", navLabel: "Hospital appointment booking system",
    title: "Hospital appointment booking system for India",
    description: "Online and WhatsApp appointment booking for hospitals and multi-doctor clinics in India: per-doctor schedules, payments and a live queue, scoped properly first.",
    eyebrow: "Hospitals and multi-doctor clinics", h1: "Hospital appointment booking system",
    lede: "A hospital is not a bigger clinic. It has departments, many doctors on different schedules, and patients who want the right doctor. We scope those properly first, then build online and WhatsApp booking with per-doctor availability, payments and a live queue for each desk.",
    sections: [
      { h: "What changes at hospital scale", p: [
        "Doctors have their own days, hours, fees and visit types. Patients choose by department, doctor or symptom. Several front desks need their own queue view, and the management team wants a single picture of the day.",
        "We model those relationships up front instead of bolting them on, which keeps booking, queues and reminders consistent.",
      ] },
      { h: "What we cover", p: ["Typical scope for a multi-doctor setup:"], bullets: [
        "Department and doctor pages with real availability",
        "Per-doctor schedules, leave and day overrides",
        "Online payment, refunds and reminders",
        "A WhatsApp assistant that routes to the right doctor",
        "Role-based access for desks and management",
      ] },
      { h: "Records, billing and the rest", p: ["We start with booking, queues and payments, because that is where a hospital feels the pain first. Patient records, prescriptions and insurance billing can follow as the next phase, scoped with you, or we connect to the hospital information system you already run. We will tell you plainly what is built, and what is planned."] },
    ],
    faqs: [
      { q: "Have you built this for a large hospital?", a: "Our live deployment is a single-doctor orthopaedic clinic. For multi-doctor hospitals we scope together first, and start with a pilot department." },
      { q: "Can you connect to our hospital information system?", a: "Usually, depending on the interface it exposes. We confirm before committing, or build the records side ourselves as a later phase." },
      { q: "Can patients choose the doctor?", a: "Yes. Booking can be by doctor, department or both." },
      { q: "How long does a pilot take?", a: "Usually a few weeks for one department, depending on integrations." },
    ],
    proof: ORTHO, related: ["/clinic-management-software-india", "/appointment-booking-software-for-clinics", "/clinic-appointment-booking-software-andhra-pradesh"],
    keywords: ["hospital appointment booking system India", "multi doctor clinic appointment software", "doctor schedule management software"],
    ctaMessage: "Hi, we run a hospital and want to scope appointment booking.", ...clinicCta,
  },
  {
    kind: "landing", cluster: "clinic", slug: "clinic-management-software-india",
    path: "/clinic-management-software-india", navLabel: "Clinic front desk software",
    title: "Clinic front desk & queue software for India",
    description: "A live token queue, walk-ins, payments, reminders and patient list for a clinic front desk, with online and WhatsApp booking feeding it.",
    eyebrow: "Clinic operations", h1: "Clinic front desk and queue management software",
    lede: "This starts with the desk, where a clinic's day begins. A live token queue, walk-in entry, collections, reminders, a patient list and a broadcast tool, fed by online and WhatsApp booking, so the front desk runs from one screen.",
    sections: [
      { h: "What the desk gets", p: ["The screen reception actually works from:"], bullets: [
        "Today's queue with tokens, status and who is next",
        "Walk-ins added in seconds, with a token issued",
        "Cash and online payments tracked, refunds shown",
        "A switch for the doctor being in, running late or away, shown live to patients",
        "A patient list, a calendar and a broadcast tool for notices",
      ] },
      { h: "Records, prescriptions and billing", p: ["The front desk comes first. Patient records, prescriptions and insurance billing can be built as the next phase, scoped with you, or we connect to the records software you already use. Either way, the desk screen is where your day starts."] },
      { h: "Staff training included", p: ["We write an illustrated handbook for your reception and run the first day with them. A good tool the desk does not trust is worse than none, so we spend time on that."] },
    ],
    faqs: [
      { q: "Can you build medical records, prescriptions and billing too?", a: "Yes. We start with booking, queue and payments, and add records, prescriptions and billing as the next phase, scoped with you." },
      { q: "Does it work on a phone or tablet?", a: "Yes. The desk screen works on desktop, tablet and phone." },
      { q: "Can several staff use it at once?", a: "Yes. Updates appear live for everyone logged in." },
    ],
    proof: ORTHO, related: ["/appointment-booking-software-for-clinics", "/hospital-appointment-booking-system", "/guides/clinic-appointment-booking-software-buyers-checklist"],
    keywords: ["clinic management software India", "token queue management clinic", "clinic front desk software"],
    ctaMessage: "Hi, I want to know about front desk and queue software for my clinic.", ...clinicCta,
  },
  {
    kind: "landing", cluster: "clinic", slug: "whatsapp-appointment-booking-for-clinics",
    path: "/whatsapp-appointment-booking-for-clinics", navLabel: "WhatsApp appointment booking for clinics",
    title: "WhatsApp appointment booking for clinics in India",
    description: "Let patients book, reschedule, cancel and pay on your clinic's WhatsApp in Telugu, Hindi or English, with approved reminders and a live queue behind it.",
    eyebrow: "WhatsApp for clinics", h1: "WhatsApp appointment booking for clinics",
    lede: "Patients already message clinics on WhatsApp. We turn that into booking: they pick a day and time with buttons, pay to confirm, and receive a token and a reminder, all in Telugu, Hindi or English. The booking lands in your front desk queue without anyone typing it in.",
    sections: [
      { h: "How a booking looks on the patient's phone", p: [
        "A patient says hello. The assistant offers buttons for booking, timings, fees and location. Booking offers the next open days and times, asks for the basics, holds the slot and sends a payment link. When the payment lands, a confirmation with the token arrives.",
      ] },
      { h: "What makes it safe to run", p: [
        "We use Meta's official WhatsApp Business Platform on your own number, with templates Meta has approved for confirmations, reminders and notices. Sensitive actions such as cancelling need a one-time code sent to the patient's own WhatsApp. Every message's delivery status is logged, so a failure is visible.",
      ] },
      { h: "What it costs to run", p: ["We build and connect it. Meta bills the clinic directly for business-started messages, and we design the flows to keep that sensible."] },
    ],
    faqs: [
      { q: "Do patients need to install anything?", a: "No. They just message the clinic's WhatsApp number." },
      { q: "Can I keep my current number?", a: "Usually, with some constraints about using the regular app on the same number. We check at the start." },
      { q: "Can a person take over from the assistant?", a: "Yes. The assistant handles routine bookings and questions, and your team handles the rest." },
      { q: "Does it work in Telugu?", a: "Yes, along with Hindi and English." },
    ],
    proof: { ...ORTHO, title: "Ramachandra Ortho Care's WhatsApp assistant", img: "/case/ortho/rc-chat-m.webp", alt: "Clinic assistant chat with quick reply buttons" },
    related: ["/whatsapp-business-automation", "/appointment-booking-software-for-clinics", "/guides/whatsapp-reminders-for-clinic-appointments"],
    keywords: ["WhatsApp appointment booking for clinics", "WhatsApp booking bot clinic", "WhatsApp appointment reminders clinic"],
    ctaMessage: "Hi, I want WhatsApp appointment booking for my clinic.", ...clinicCta,
  },
  // ---------------------------------------------------------------- clinic: specialities
  {
    kind: "landing", cluster: "clinic", slug: "orthopedic-clinic-appointment-booking-software",
    path: "/orthopedic-clinic-appointment-booking-software", navLabel: "Orthopaedic clinic booking software",
    title: "Orthopedic clinic appointment booking software",
    description: "Booking, follow-up visits, WhatsApp and online payment for orthopaedic and trauma clinics, from the team running one live in Visakhapatnam.",
    eyebrow: "Orthopaedic and trauma", h1: "Orthopedic clinic appointment booking software",
    lede: "Orthopaedic clinics have a distinctive rhythm: first consultations, review visits after a fracture or surgery, and walk-in trauma. Our live deployment is exactly this, a Visakhapatnam orthopaedic clinic, so these are problems we have already met.",
    sections: [
      { h: "New, returning and review visits", p: [
        "The system distinguishes first visits, returning patients and free review visits within a set window of a previous consultation, each with its own fee and flow. Patients see the right price before they pay, and the front desk is not arguing about it at the counter.",
      ] },
      { h: "Walk-ins and trauma days", p: ["Walk-ins can be added to the same queue in seconds, so a trauma patient who turns up unannounced is not outside the system. A switch shows patients when the doctor is in, late or away."] },
      { h: "Reminders that fit follow-ups", p: ["A reminder goes out the evening before, and a missed appointment rolls forward to the next working day without the patient having to rebook."] },
    ],
    faqs: [
      { q: "Can free review visits be handled?", a: "Yes. Review visits within a set number of days can be free and are handled as their own visit type." },
      { q: "Does it handle walk-in trauma patients?", a: "Yes. Walk-ins join the same live queue as booked patients." },
      { q: "Is there a Telugu version?", a: "Yes, across the site and the WhatsApp assistant." },
    ],
    proof: ORTHO, related: ["/appointment-booking-software-for-clinics", "/clinic-appointment-booking-software-visakhapatnam", "/physiotherapy-clinic-appointment-booking-software"],
    keywords: ["orthopedic clinic appointment software", "orthopaedic clinic booking system", "bone and joint clinic appointment booking"],
    ctaMessage: "Hi, I run an orthopaedic clinic and want to know about your booking system.", ...clinicCta,
  },
  {
    kind: "landing", cluster: "clinic", slug: "dental-clinic-appointment-booking-software",
    path: "/dental-clinic-appointment-booking-software", navLabel: "Dental clinic booking software",
    title: "Dental clinic appointment booking software in India",
    description: "Online and WhatsApp booking, reminders and deposits for dental clinics: multi-visit treatments, recalls and fewer empty chairs.",
    eyebrow: "Dental clinics", h1: "Dental clinic appointment booking software",
    lede: "Dental care runs on multi-visit treatments and recall reminders, and an empty chair is expensive. We configure online and WhatsApp booking with pay-to-confirm, reminders and follow-up scheduling around how your dental clinic actually works.",
    sections: [
      { h: "How dental differs from a general clinic", p: [
        "A root canal is three visits, an aligner review is every few weeks, and a scale and polish is due again in six months. Booking has to handle visit sequences and recalls, not just single consults.",
        "We have not yet deployed this in a dental practice. Our live system runs an orthopaedic clinic, and we are upfront that dental configuration is scoped with you: visit types, durations, chair or dentist schedules and recall rules.",
      ] },
      { h: "What we would set up with you", p: [], bullets: [
        "Visit types with their own durations, such as consult, cleaning or procedure",
        "Pay-to-confirm or a smaller booking deposit for longer slots",
        "Reminders the evening before, and recall messages when a check-up is due",
        "A WhatsApp assistant for booking, rescheduling and directions",
        "A live queue for walk-in pain cases and emergencies",
      ] },
      { h: "Why deposits matter here", p: ["A no-show on a long procedure slot costs real money. Taking payment to confirm, or a deposit, moves the commitment to the patient's side before the day."] },
    ],
    faqs: [
      { q: "Have you built this for a dental clinic?", a: "Not yet. Our live deployment is an orthopaedic clinic, and we configure dental flows with you rather than pretend otherwise." },
      { q: "Can it handle recall reminders for check-ups?", a: "Yes, as a scheduled reminder, scoped with you." },
      { q: "Can a deposit be taken instead of the full fee?", a: "Yes. The amount to confirm a slot is configurable." },
    ],
    proof: ORTHO, related: ["/appointment-booking-software-for-clinics", "/dermatology-clinic-appointment-booking-software", "/guides/how-to-reduce-no-shows-at-a-clinic"],
    keywords: ["dental clinic appointment booking software", "dentist appointment software India", "dental clinic WhatsApp booking"],
    ctaMessage: "Hi, I run a dental clinic and want online and WhatsApp booking.", ...clinicCta,
  },
  {
    kind: "landing", cluster: "clinic", slug: "dermatology-clinic-appointment-booking-software",
    path: "/dermatology-clinic-appointment-booking-software", navLabel: "Skin clinic booking software",
    title: "Dermatology & skin clinic appointment booking software",
    description: "Discreet online and WhatsApp booking for dermatology, skin and aesthetic clinics: consult types, procedure slots, reminders and deposits.",
    eyebrow: "Skin and aesthetic clinics", h1: "Dermatology and skin clinic appointment booking software",
    lede: "Skin and aesthetic clinics mix quick consults with longer procedure sessions, and patients like privacy and a polished experience. We set up booking that looks as considered as your clinic, with deposits for long slots and WhatsApp for the follow-ups.",
    sections: [
      { h: "Consults, procedures and follow-ups", p: [
        "A first consult, a laser session and a follow-up differ in length, price and preparation. We model them as separate visit types so patients choose what they need and the doctor's day is not mis-sized.",
        "Our live system runs an orthopaedic clinic. We have also designed a dermatology clinic concept site, and we configure skin-specific flows with you rather than assume.",
      ] },
      { h: "A front door that matches the brand", p: ["Skin clinics sell on trust and look. We design the booking pages in your clinic's own identity, not a template."] },
      { h: "Discretion", p: ["Patient details are used to run the clinic only. Reminders are written to be discreet and avoid naming a procedure in a message where you prefer that."] },
    ],
    faqs: [
      { q: "Can different procedures have different slot lengths and fees?", a: "Yes, each is configured as its own visit type." },
      { q: "Can I take a deposit for procedures?", a: "Yes. The amount to confirm a slot is configurable." },
      { q: "Can reminders avoid naming the treatment?", a: "Yes. Message wording is yours to approve." },
    ],
    proof: ORTHO, related: ["/appointment-booking-software-for-clinics", "/dental-clinic-appointment-booking-software", "/branding-and-packaging-design-visakhapatnam"],
    keywords: ["dermatology clinic appointment software", "skin clinic booking system", "aesthetic clinic appointment booking India"],
    ctaMessage: "Hi, I run a skin clinic and want online and WhatsApp booking.", ...clinicCta,
  },
  {
    kind: "landing", cluster: "clinic", slug: "physiotherapy-clinic-appointment-booking-software",
    path: "/physiotherapy-clinic-appointment-booking-software", navLabel: "Physiotherapy booking software",
    title: "Physiotherapy clinic appointment booking software",
    description: "Recurring session booking, reminders and WhatsApp for physiotherapy clinics: course-based visits, rescheduling and fewer missed sessions.",
    eyebrow: "Physiotherapy", h1: "Physiotherapy clinic appointment booking software",
    lede: "Physiotherapy is a course of repeat sessions, and the course falls apart when patients miss a few. We set up booking with easy rescheduling, a reminder the evening before each session, and WhatsApp so patients can move a slot without calling.",
    sections: [
      { h: "Repeat sessions without repeat admin", p: [
        "Patients typically come several times a week for a few weeks. Rebooking each one by phone is the desk's least favourite job. We configure session booking so a patient can book their next visit straight after one, and reschedule on WhatsApp.",
        "Our live deployment is an orthopaedic clinic, a close neighbour. For physiotherapy specifically, series booking and package pricing are scoped with you.",
      ] },
      { h: "Reminders do the heavy lifting", p: ["A reminder the evening before, and an automatic roll to the next working day if a session is missed, keep the course on track."] },
      { h: "Works alongside orthopaedics", p: ["Many physiotherapy practices share patients with an orthopaedic clinic. The same system can run both desks."] },
    ],
    faqs: [
      { q: "Can patients book a series of sessions?", a: "That is scoped with you. Today our live system books one visit at a time with easy follow-up booking, and a package flow can be added." },
      { q: "Can patients reschedule themselves?", a: "Yes, on the web or on WhatsApp, after a one-time code to prove it is them." },
      { q: "Can it run in more than one location?", a: "Yes, with each location's schedule configured separately." },
    ],
    proof: ORTHO, related: ["/orthopedic-clinic-appointment-booking-software", "/appointment-booking-software-for-clinics", "/guides/whatsapp-reminders-for-clinic-appointments"],
    keywords: ["physiotherapy clinic appointment software", "physio booking system India", "physiotherapy WhatsApp booking"],
    ctaMessage: "Hi, I run a physiotherapy clinic and want booking and reminders.", ...clinicCta,
  },
  {
    kind: "landing", cluster: "clinic", slug: "diagnostic-lab-appointment-booking-software",
    path: "/diagnostic-lab-appointment-booking-software", navLabel: "Diagnostic lab booking software",
    title: "Diagnostic lab & scan centre appointment booking",
    description: "Slot booking, WhatsApp confirmations and online payment for diagnostic labs and scan centres: test slots, home collection requests and reminders.",
    eyebrow: "Labs and scan centres", h1: "Diagnostic lab and scan centre appointment booking",
    lede: "Labs and scan centres lose time to calls asking for slots, fasting instructions and report timings. We set up online and WhatsApp slot booking with payment, preparation instructions in the confirmation and a live queue for the counter.",
    sections: [
      { h: "Slots and preparation, in one message", p: [
        "A fasting blood test and an MRI need different slots and different instructions. The confirmation carries the right preparation note, so the patient arrives ready and the technician is not rescheduling on the spot.",
        "This is a configuration we scope with you. Our live deployment is a clinic, and we are upfront that diagnostic-specific flows, such as per-machine schedules or home collection, are discussed before building.",
      ] },
      { h: "What can be set up", p: [], bullets: [
        "Test or scan type with its own slot length and price",
        "Prepayment or deposit to confirm",
        "Preparation instructions inside the confirmation message",
        "A counter queue for walk-in tests",
        "Reminders and rescheduling over WhatsApp",
      ] },
    ],
    faqs: [
      { q: "Can it handle home sample collection?", a: "It can be scoped as a request flow with a collection window. We discuss logistics with you first." },
      { q: "Can each scan machine have its own schedule?", a: "Yes, each resource gets its own schedule." },
      { q: "Do you deliver reports?", a: "No. This handles booking, payment and the queue, not report delivery." },
    ],
    proof: ORTHO, related: ["/clinic-management-software-india", "/appointment-booking-software-for-clinics", "/whatsapp-appointment-booking-for-clinics"],
    keywords: ["diagnostic lab appointment booking software", "scan centre appointment booking", "pathology lab slot booking system"],
    ctaMessage: "Hi, I run a diagnostic lab and want slot booking.", ...clinicCta,
  },
  // ---------------------------------------------------------------- web: places and types
  {
    kind: "landing", cluster: "web", slug: "software-development-company-visakhapatnam",
    path: "/software-development-company-visakhapatnam", navLabel: "Software development in Vizag",
    title: "Software development company in Visakhapatnam",
    description: "A Vizag software studio building custom web software, booking and ordering systems, dashboards and integrations for businesses across India.",
    eyebrow: "Custom software", h1: "Software development company in Visakhapatnam",
    lede: "We build custom software for businesses in Visakhapatnam and across India: booking systems, ordering platforms, admin dashboards and the integrations between them. It is designed and built by the same team, and we run what we build, so we care how it behaves in daily use.",
    sections: [
      { h: "What we build", p: [], bullets: [
        "Appointment and queue systems for clinics",
        "Table ordering and loyalty systems for restaurants and bars",
        "Admin dashboards with live data and role-based access",
        "WhatsApp, payment and point-of-sale integrations",
        "Internal tools that replace spreadsheets and chat threads",
      ] },
      { h: "How we work", p: [
        "We start from the real workflow and prototype early so you react to screens, not documents. We build on a modern stack with a managed database and keep a test suite on the parts where mistakes cost money, such as payments and double bookings.",
      ] },
      { h: "Why a Vizag studio", p: ["Being local means we can meet your team and see the problem in person. Most of our work after that happens remotely, which is how we also serve clients across Andhra Pradesh and the rest of India."] },
    ],
    faqs: [
      { q: "What kind of software do you build?", a: "Web-based business software: booking, ordering, dashboards and integrations. We do not do large enterprise rollouts." },
      { q: "Do you maintain what you build?", a: "Yes. We stay on for fixes, monitoring and changes after launch." },
      { q: "Who owns the code?", a: "That is agreed at the start. We prefer clear ownership and documentation so you are never locked in." },
      { q: "How do you price projects?", a: "We scope first and quote a fixed plan, rather than quote blind." },
    ],
    proof: SOMAA, related: ["/web-development-company-visakhapatnam", "/mobile-app-and-pwa-development-visakhapatnam", "/guides/how-to-choose-a-web-development-company-in-vizag"],
    keywords: ["software development company Visakhapatnam", "custom software development Vizag", "web software developers Vizag"],
    ctaMessage: "Hi, we are looking for a software development partner in Vizag.", ctaLabel: "Message us on WhatsApp", accent: "#8a6d2f",
  },
  {
    kind: "landing", cluster: "web", slug: "mobile-app-and-pwa-development-visakhapatnam",
    path: "/mobile-app-and-pwa-development-visakhapatnam", navLabel: "App and PWA development in Vizag",
    title: "Mobile app & PWA development in Visakhapatnam",
    description: "Progressive web apps and Android apps from a Vizag studio: installable, fast, offline-friendly and built on the same stack as your website.",
    eyebrow: "Apps and PWAs", h1: "Mobile app and PWA development in Visakhapatnam",
    lede: "Many businesses do not need a store-listed app. A progressive web app installs from the browser, works offline where it matters and costs far less to run. When a native Android app is the right answer, we build that too. Both come from our Visakhapatnam studio.",
    sections: [
      { h: "PWA first, native when it earns it", p: [
        "A PWA gives you an installable icon, push-style reminders and offline use without app store reviews, updates or a separate codebase. For booking, ordering and dashboards, it is usually the better start.",
        "We chose a native Android app for one of our own products, a notification filter that needs system-level access a browser cannot give. That is the kind of case where native is justified.",
      ] },
      { h: "Our own proof", p: ["Percentyle, an exam-prep product we built and run, is a PWA, and Pingless is an Android app. They are our own products rather than client work, and they show the range we handle."] },
      { h: "What to bring us", p: ["Tell us what the app must do and who uses it. We will say plainly whether a PWA, a native app or just a good website is the right call."] },
    ],
    faqs: [
      { q: "Do I need a Play Store app?", a: "Often not. A PWA can cover booking, ordering and dashboards. We tell you honestly which you need." },
      { q: "Can you build an iPhone app?", a: "iPhone users can install a PWA. A native iOS build is scoped separately." },
      { q: "Do PWAs work offline?", a: "Parts can, depending on what the app does. We design the offline behaviour with you." },
    ],
    proof: { label: "Our own product", title: "Percentyle, a PWA we built and run", text: "A CAT exam-prep progressive web app, live at percentyle.in.", href: "https://percentyle.in", cta: "Visit Percentyle", img: "/case/percentyle/home.webp", alt: "Percentyle exam-prep web app home page", external: true },
    related: ["/software-development-company-visakhapatnam", "/web-development-company-visakhapatnam", "/guides/what-drives-website-cost-in-india"],
    keywords: ["mobile app development Visakhapatnam", "PWA development India", "Android app developers Vizag"],
    ctaMessage: "Hi, we want to talk about an app or PWA.", ctaLabel: "Message us on WhatsApp", accent: "#8a6d2f",
  },
  {
    kind: "landing", cluster: "web", slug: "ecommerce-website-development-visakhapatnam",
    path: "/ecommerce-website-development-visakhapatnam", navLabel: "E-commerce websites in Vizag",
    title: "E-commerce website development in Visakhapatnam",
    description: "Design-led online stores for handcrafted and premium products from a Vizag studio: storytelling product pages, payments and a fast checkout.",
    eyebrow: "Online stores", h1: "E-commerce website development in Visakhapatnam",
    lede: "We design and build online stores that sell on story and craft, not just a price grid. Product pages that feel like the object, a fast checkout on a phone, and payments set up properly, from a Visakhapatnam studio that also does brand and packaging.",
    sections: [
      { h: "Stores for products that deserve a story", p: [
        "Handmade, regional and premium products sell when buyers can see where something comes from. We design product pages around that, then make the buying part quick, since most shoppers are on a phone.",
        "Our concept study Karu, a marketplace for handcrafted Indian art, is a self-initiated build rather than client work, and shows the approach.",
      ] },
      { h: "What is included", p: [], bullets: [
        "Custom store design, not a stock theme",
        "Product, collection and story pages built for search",
        "UPI and card payments, with order and refund handling",
        "Packaging and brand design when you need it too",
        "Analytics and search console set up at launch",
      ] },
      { h: "Brand and store together", p: ["Because we design packaging and brand identity, the store, the box and the Instagram post look like one company."] },
    ],
    faqs: [
      { q: "Do you build on Shopify or custom?", a: "We choose what fits your catalogue and budget, and tell you why." },
      { q: "Can you set up payments and shipping?", a: "Yes, with the integrations that suit your volume." },
      { q: "Will the store rank on Google?", a: "We build the technical foundations properly. Rankings still depend on content and competition." },
    ],
    proof: { label: "Self-initiated concept", title: "Karu, a handcrafted-art marketplace", text: "A story-first marketplace concept for Indian craft, built to show our approach to premium commerce.", href: "https://karu.made-by-ac.com", cta: "Visit the concept", img: "/labs/karu/cover.webp", alt: "Karu marketplace concept", external: true },
    related: ["/web-development-company-visakhapatnam", "/branding-and-packaging-design-visakhapatnam", "/guides/what-drives-website-cost-in-india"],
    keywords: ["ecommerce website development Visakhapatnam", "online store design Vizag", "Shopify developer Vizag"],
    ctaMessage: "Hi, we want an online store for our products.", ctaLabel: "Message us on WhatsApp", accent: "#a2512d",
  },
  {
    kind: "landing", cluster: "web", slug: "ui-ux-design-company-visakhapatnam",
    path: "/ui-ux-design-company-visakhapatnam", navLabel: "UI/UX design in Vizag",
    title: "UI/UX design company in Visakhapatnam",
    description: "Interface and experience design for websites and products from a Vizag studio that builds what it designs, with real screens early and no hand-off gap.",
    eyebrow: "UI and UX design", h1: "UI/UX design company in Visakhapatnam",
    lede: "We design interfaces for websites, apps and internal tools, and we ship them. That means designs that survive contact with code: sensible spacing, real states, accessible contrast and a layout that works at phone width first.",
    sections: [
      { h: "How we design", p: [
        "We start from the task a person is trying to finish, sketch fast, and put real screens in front of you early at phone and desktop width. We write real copy rather than lorem ipsum, since layout depends on it.",
      ] },
      { h: "What you get", p: [], bullets: [
        "Flows and wireframes for the key journeys",
        "A visual system: colour, type, spacing and components",
        "High-fidelity screens at phone and desktop width",
        "A working front end if you want us to build it",
        "A review against accessibility and usability checklists",
      ] },
      { h: "Design that is built", p: ["Because the same team builds, nothing is lost in a hand-off. Our case studies show the result: a clinic's booking flow in three languages and a restobar's ordering experience."] },
    ],
    faqs: [
      { q: "Do you do design only, without development?", a: "Yes, though most clients take both since the hand-off is where ideas are lost." },
      { q: "Do you design for Indian languages?", a: "Yes, including Telugu typography and layouts that hold up with longer scripts." },
      { q: "How long does a design project take?", a: "Weeks for a focused product or site. We give you a schedule before starting." },
    ],
    proof: ORTHO, related: ["/web-development-company-visakhapatnam", "/branding-and-packaging-design-visakhapatnam", "/website-development-company-hyderabad"],
    keywords: ["UI UX design company Visakhapatnam", "web design agency Vizag", "app design studio Vizag"],
    ctaMessage: "Hi, we are looking for a UI/UX design studio.", ctaLabel: "Message us on WhatsApp", accent: "#8a6d2f",
  },
  {
    kind: "landing", cluster: "web", slug: "website-development-company-andhra-pradesh",
    path: "/website-development-company-andhra-pradesh", navLabel: "Web development in Andhra Pradesh",
    title: "Website development company in Andhra Pradesh",
    description: "Design and development for businesses across Andhra Pradesh: Vijayawada, Guntur, Tirupati, Rajahmundry and beyond, built in Telugu and English by a Vizag studio.",
    eyebrow: "Andhra Pradesh", h1: "Website development company in Andhra Pradesh",
    lede: "We build websites and web apps for businesses across Andhra Pradesh, from our studio in Visakhapatnam. Clients in Vijayawada, Guntur, Tirupati, Rajahmundry, Kakinada and Nellore work with us over video, and we are happy to travel when it helps.",
    sections: [
      { h: "Built for Andhra customers", p: [
        "Your customers read Telugu as easily as English, pay by UPI and arrive from WhatsApp links. We design for all three: bilingual pages that render properly, fast loads on mid-range phones and payment and WhatsApp flows that feel native.",
      ] },
      { h: "Industries we know", p: ["We have built for clinics, restaurants and bars, and consumer brands. Each has habits we have already learned, and we bring them to your project."] },
      { h: "Working remotely, properly", p: ["Weekly video check-ins, a shared board you can see, and real screens early. Most clients never feel the distance."] },
    ],
    faqs: [
      { q: "Do you work with businesses outside Visakhapatnam?", a: "Yes. We work across Andhra Pradesh and India over video." },
      { q: "Can the website be in Telugu?", a: "Yes. We build bilingual sites, written to be read, not machine translated." },
      { q: "Do you build for small local businesses?", a: "Yes. A focused site is often the best start." },
    ],
    proof: SOMAA, related: ["/web-development-company-visakhapatnam", "/website-development-company-hyderabad", "/clinic-appointment-booking-software-andhra-pradesh"],
    keywords: ["website development company Andhra Pradesh", "web design Vijayawada", "web development Guntur Tirupati"],
    ctaMessage: "Hi, we are an Andhra Pradesh business looking for a website partner.", ctaLabel: "Message us on WhatsApp", accent: "#8a6d2f",
  },
  {
    kind: "landing", cluster: "web", slug: "website-development-company-hyderabad",
    path: "/website-development-company-hyderabad", navLabel: "Web development for Hyderabad",
    title: "Website development company for Hyderabad businesses",
    description: "Design-led websites and web apps for Hyderabad and Telangana businesses, with Telugu support, built by a Visakhapatnam studio working remotely.",
    eyebrow: "Hyderabad and Telangana", h1: "Website development company for Hyderabad and Telangana",
    lede: "We build design-led websites and web apps for businesses in Hyderabad and across Telangana, working remotely from Visakhapatnam. If you want one team that designs and builds together, and writes Telugu and Hindi properly, we are a good fit.",
    sections: [
      { h: "The people drawing it, not an account manager", p: ["You speak to the people drawing and building your site. That keeps decisions quick and the design intact all the way to code."] },
      { h: "Multilingual from the start", p: ["Telugu, Hindi and English, with type that renders well and layouts that cope with longer scripts. Our campaign work for a Hyderabad and Bengaluru brand included custom Telugu typography."] },
      { h: "What we are not", p: ["We are not a large Hyderabad agency with a floor of developers. We are a focused studio, which means senior attention on every project and a limit on how many we take at once."] },
    ],
    faqs: [
      { q: "Do you have a Hyderabad office?", a: "No. We are based in Visakhapatnam and work with Hyderabad clients remotely, travelling when it is useful." },
      { q: "Do you do Telugu and Hindi websites?", a: "Yes, written and typeset properly." },
      { q: "What do you build?", a: "Business sites, web apps, booking and ordering systems and brand work." },
    ],
    proof: { label: "Recent work", title: "Innovolt, campaigns for Hyderabad and Bengaluru", text: "Regional-language campaign design, including custom Telugu typography, for a commercial EV marketplace.", href: "/work/innovolt", cta: "Read the case study", img: "/images/Hyd'Tel.webp", alt: "Telugu campaign creative for Hyderabad" },
    related: ["/web-development-company-visakhapatnam", "/website-development-company-andhra-pradesh", "/clinic-appointment-booking-software-hyderabad"],
    keywords: ["website development company Hyderabad", "web design agency Telangana", "Telugu website design"],
    ctaMessage: "Hi, we are a Hyderabad business looking for a website partner.", ctaLabel: "Message us on WhatsApp", accent: "#8a6d2f",
  },
  // ---------------------------------------------------------------- restaurant
  {
    kind: "landing", cluster: "restaurant", slug: "restaurant-qr-ordering-system-visakhapatnam",
    path: "/restaurant-qr-ordering-system-visakhapatnam", navLabel: "QR ordering for Vizag restaurants",
    title: "QR ordering system for Visakhapatnam restaurants & bars",
    description: "Table QR ordering, a brand-matched digital menu and loyalty for restaurants, bars and cafes in Vizag, from the studio behind a live local pilot.",
    eyebrow: "Vizag restaurants and bars", h1: "QR ordering system for restaurants and bars in Visakhapatnam",
    lede: "We build table QR ordering for restaurants, bars and cafes in Visakhapatnam. Our live pilot is a Vizag restobar, so we know what a busy Friday service, a loud room and a kitchen already on a point-of-sale actually demand.",
    sections: [
      { h: "Built in a Vizag room", p: [
        "Somaa, a coastal-Andhra restobar with live music, runs its at-table ordering on what we built: per-table codes, a shared table cart, an AI host that knows the menu, and a loyalty and feedback loop. We tuned it on a real floor, not in a demo.",
      ] },
      { h: "Where it helps most", p: [], bullets: [
        "Busy evenings when guests wait just to be noticed",
        "Large tables that order in pieces",
        "Bars that want pairings and second rounds suggested",
        "Regulars you want to recognise on birthdays and anniversaries",
      ] },
      { h: "Local and in person", p: ["We can come to your venue, look at the floor and menu, and run a pilot on a few tables before the whole room."] },
    ],
    faqs: [
      { q: "Is it an app guests must download?", a: "No. They scan the table code and the menu opens in the browser." },
      { q: "Can it work with my point-of-sale?", a: "Our pilot forwards orders to a restaurant point-of-sale. Others are scoped case by case." },
      { q: "Do you replace waiters?", a: "No. It frees them to do hospitality and helps each one sell more." },
    ],
    proof: SOMAA, related: ["/restaurant-qr-ordering-system", "/digital-menu-for-restaurants-and-bars", "/guides/qr-menu-vs-qr-ordering-for-restaurants"],
    keywords: ["QR ordering system Visakhapatnam", "restaurant software Vizag", "digital menu Vizag restaurants"],
    ctaMessage: "Hi, we run a restaurant in Vizag and want QR ordering.", ctaLabel: "Talk to us on WhatsApp", accent: "#a8651c",
  },
  {
    kind: "landing", cluster: "restaurant", slug: "digital-menu-for-restaurants-and-bars",
    path: "/digital-menu-for-restaurants-and-bars", navLabel: "Digital menu for restaurants",
    title: "Digital menu for restaurants & bars, matched to your brand",
    description: "A QR digital menu with photos, prices, veg and bar flags and daily specials, designed in your brand and upgradeable to full table ordering.",
    eyebrow: "Digital menus", h1: "A digital menu for restaurants and bars that looks like your place",
    lede: "Most QR menus are a PDF on a phone. We design a digital menu that matches your room: photography, prices, veg and bar flags, bestsellers and daily specials, fast to load and easy to change. And if you want guests to order from it later, the same menu upgrades to full table ordering.",
    sections: [
      { h: "A menu you can change in minutes", p: ["Mark a dish sold out, add today's special or change a price, and every table sees it straight away. No reprinting and no outdated PDF."] },
      { h: "What goes into it", p: [], bullets: [
        "Dish photography and descriptions that sell",
        "Veg, non-veg and bar flags that are clear at a glance",
        "Bestsellers and daily specials surfaced first",
        "Your colours and type, not a generic template",
        "A path to ordering and loyalty when you are ready",
      ] },
      { h: "Menu first, ordering later", p: ["Starting with a menu is a low-risk first step. When you want guests to order, group carts, an AI host and loyalty can build on the same foundation."] },
    ],
    faqs: [
      { q: "Is a digital menu the same as QR ordering?", a: "No. A menu shows dishes. Ordering takes the order. We can start with one and grow into the other." },
      { q: "Can I update prices myself?", a: "Yes, from a simple admin screen." },
      { q: "Does it work without an app?", a: "Yes. It opens in the phone's browser from the table code." },
    ],
    proof: SOMAA, related: ["/restaurant-qr-ordering-system", "/restaurant-qr-ordering-system-visakhapatnam", "/guides/qr-menu-vs-qr-ordering-for-restaurants"],
    keywords: ["digital menu for restaurants India", "QR code menu for restaurants", "digital menu for bars"],
    ctaMessage: "Hi, we want a digital menu for our restaurant.", ctaLabel: "Talk to us on WhatsApp", accent: "#a8651c",
  },
];
